import type { Metadata } from "next";
import { Brygada_1918, Mulish, Outfit } from "next/font/google";
import "./globals.css";

const brygada = Brygada_1918({ subsets: ["latin"], weight: ["400", "500", "600", "700"], display: "swap", variable: "--font-brygada" });
const mulish = Mulish({ subsets: ["latin"], weight: ["200", "300", "400", "500", "600", "700", "800", "900"], display: "swap", variable: "--font-mulish" });
const outfit = Outfit({ subsets: ["latin"], weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], display: "swap", variable: "--font-outfit" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${brygada.variable} ${mulish.variable} ${outfit.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
